---
name: exercise-1

on:
    push:
        - main

jobs:
    learning:
        runs-on: ubuntu-latest
        steps:
            - name: learning
              run: "echo hello how are you"
            - name: list env
              run: printenv
                
